// MONGO URI:
mongodb+srv://<username>:<password>@cluster0.dmwtz.mongodb.net/<dbname>>?retryWrites=true&w=majority

// NETWORK ACCESS > IP ADDRESS
- your ip address if you only want local connections
OR  if you want connections from anywhere
- 0.0.0.0/0  (includes your current IP address)	

// TESTING A ROUTE: 
// POSTMAN -> POST ::: BODY ::: JSON
http://localhost:5002/api/auth/register

// TESTING THE JWT TOKEN (PROTECTING A ROUTE)
// POSTMAN
// GET http://localhost:5002/api/auth/test
- Grab the token generated by the login or register request
- Then go to HEADERS and add the 
1) 'Authorization' key 
2) + their token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6...


// FRONTEND
// start new apps with React and Redux 
// npx create-react-app <app-name> --template redux
cd ../
npx create-react-app frontend --template redux
// FRONT END PACKAGES
npm i axios react-router-dom redux-devtools-extension redux-thunk
// Material UI
npm install @mui/material @emotion/react @emotion/styled
