version: "3"

services:
  # 1st container, we select the name, 'lb' for load balancer
  # it will be an external container and the only one accesible to
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  # another container
  nodeapp1:
    image: nodeapp
    environment:
      - APPID=1111
  nodeapp2:
    image: nodeapp
    environment:
      - APPID=2222
  nodeapp3:
    image: nodeapp
    environment:
      - APPID=3333
